const sequelize = require("../../../db");
const { DataTypes } = require("sequelize");

const UserTable = sequelize.define("user", {
  id: { type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true },
  avatar: { type: DataTypes.STRING, defaultValue: null },
  email: { type: DataTypes.STRING, allowNull: false },
  password: { type: DataTypes.STRING, allowNull: false },
  username: { type: DataTypes.STRING, defaultValue: null },
  fullName: { type: DataTypes.STRING, defaultValue: null },
  sex: { type: DataTypes.STRING, defaultValue: null },
  day: { type: DataTypes.INTEGER, defaultValue: null },
  month: { type: DataTypes.INTEGER, defaultValue: null },
  year: { type: DataTypes.INTEGER, defaultValue: null },
  gender: { type: DataTypes.STRING, defaultValue: null },
  country: { type: DataTypes.STRING, defaultValue: null },
  city: { type: DataTypes.STRING, defaultValue: null },
  aCodeword: { type: DataTypes.STRING, defaultValue: null },
  appearance: { type: DataTypes.STRING, defaultValue: null },
  bodyType: { type: DataTypes.STRING, defaultValue: null },
  height: { type: DataTypes.STRING, defaultValue: null },
  weight: { type: DataTypes.STRING, defaultValue: null },
  hairColor: { type: DataTypes.STRING, defaultValue: null },
  eyeColor: { type: DataTypes.STRING, defaultValue: null },
  character: { type: DataTypes.STRING, defaultValue: null },
  children: { type: DataTypes.STRING, defaultValue: null },
  religion: { type: DataTypes.STRING, defaultValue: null },
  zodiac: { type: DataTypes.STRING, defaultValue: null },
  education: { type: DataTypes.STRING, defaultValue: null },
  typesOfHobbies: { type: DataTypes.JSON, defaultValue: [] },
  hobbies: { type: DataTypes.STRING, defaultValue: null },
  alcohol: { type: DataTypes.STRING, defaultValue: null },
  smoking: { type: DataTypes.STRING, defaultValue: null },
  yourAim: { type: DataTypes.STRING, defaultValue: null },
  info: { type: DataTypes.TEXT, defaultValue: null },
  phone: { type: DataTypes.STRING, defaultValue: null },
  lat: { type: DataTypes.STRING, defaultValue: null },
  lon: { type: DataTypes.STRING, defaultValue: null },
  ofline: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isRendezvousTime: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  balance: { type: DataTypes.INTEGER, defaultValue: 0 },
  familyStatus: { type: DataTypes.STRING, defaultValue: null },
  otp: { type: DataTypes.STRING, defaultValue: null },
  view: { type: DataTypes.INTEGER, defaultValue: 0 },
  privateSex: { type: DataTypes.STRING, defaultValue: null },
  ageMin: { type: DataTypes.INTEGER, defaultValue: null },
  ageMax: { type: DataTypes.INTEGER, defaultValue: null },
  privateGeo: { type: DataTypes.JSON, defaultValue: [] },
  vip: { type: DataTypes.BOOLEAN, defaultValue: false },
  vipCreatedAt: { type: DataTypes.DATE, defaultValue: null },
  base: { type: DataTypes.BOOLEAN, defaultValue: false },
  baseCreatedAt: { type: DataTypes.DATE, defaultValue: null },
  top: { type: DataTypes.BOOLEAN, defaultValue: false },
  topBoxShadow: { type: DataTypes.STRING, defaultValue: "rgba(0,255,44,0.02)" },
  policyChat: { type: DataTypes.BOOLEAN, defaultValue: false },
  topCreatedAt: { type: DataTypes.DATE, defaultValue: null },
  isAdmin: { type: DataTypes.BOOLEAN, defaultValue: false },
  moderator: { type: DataTypes.BOOLEAN, defaultValue: false },
  isEditName: { type: DataTypes.BOOLEAN, defaultValue: false },
  isEditGeo: { type: DataTypes.BOOLEAN, defaultValue: false },
  isEditAppearance: { type: DataTypes.BOOLEAN, defaultValue: false },
  isEditAage: { type: DataTypes.BOOLEAN, defaultValue: false },
  isEditHeight: { type: DataTypes.BOOLEAN, defaultValue: false },
  isEditWeight: { type: DataTypes.BOOLEAN, defaultValue: false },
  isBanned: { type: DataTypes.BOOLEAN, defaultValue: false },
  isRendezvous: { type: DataTypes.BOOLEAN, defaultValue: false },
  isDeleteAccount: { type: DataTypes.BOOLEAN, defaultValue: false },
  verification: { type: DataTypes.BOOLEAN, defaultValue: false },
  isSearch: { type: DataTypes.BOOLEAN, defaultValue: false },
  isFt: { type: DataTypes.BOOLEAN, defaultValue: false },
});
module.exports = { UserTable };
